import "./globals.css"
import type { Metadata } from "next"
import localFont from "next/font/local"
import i18nConfig, { defaultI18nNamespaces } from "@/i18n/i18nConfig"
import initTranslations from "@/i18n"
import TranslationsProvider from "@/providers/TranslationsProvider"
import { cookies } from "next/headers"

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export function generateStaticParams() {
    return i18nConfig.locales.map((locale) => ({ locale }))
}

export default async function RootLayout({
    children,
    params,
}: Readonly<{
    children: React.ReactNode
    params: { lang: string }
}>) {
    // recommend route segement
    // const { lang } = params
    // const { t, resources } = await initTranslations(lang, defaultI18nNamespaces)

    // use cookie replace
    const cookieStorage = cookies()
    const cookieLocale = cookieStorage.get(i18nConfig.localeCookie)!.value
    const lang = cookieLocale

    const { t, resources } = await initTranslations(cookieLocale as string, defaultI18nNamespaces)

    return (
        <html lang="en">
            <body className={`min-h-[100vh] antialiased`}>
                <TranslationsProvider
                    locale={lang}
                    namespaces={defaultI18nNamespaces}
                    resources={resources}
                >
                    {children}
                </TranslationsProvider>
            </body>
        </html>
    )
}
